### ISSUE TITLE
Return value of document.get_topic_dist does not sum to 1.0

### ISSUE THREAD

**Issue by ricardog** [bab2min/tomotopy#10]
I expected the return value of `Document.get_topic_dist()` to sum to `1.0` (within some epsilon). Yet that's not what I see after training an LDA model.

```
>>> sum(lda.docs[52904].get_topic_dist())
0.05711954347498249
```

There are many documents in my model where the sum is not close to `1.0`. 

Could you please explain what the values returned by `Document.get_topic_dist()` represents?

Apologies if this is my misunderstanding.

**Comment by bab2min** [comment]
Oh, thank you for your report. it seems a bug. Could you give me more information about your situation?
How did you set `tw`, `min_cf`, `k` or `rm_top` when you initialized LDAModel?

**Comment by ricardog** [comment]
Here is how I train the model. `MyWikiCorpus` is a hacked-up version of the gensim code to process the English Wikipedia dump. 

```
    mdl = tp.LDAModel(k=150, min_cf=5, rm_top=0)
    wiki = MyWikiCorpus()
    for doc in wiki.get_texts():
        mdl.add_doc(doc)
    for i in range(1, iterations + 1):
        mdl.train(10)
```

I hope I am using the parameters correctly. 

I uploaded the model file to S3 in case it is useful for debugging (as I said it's just Wikipedia pages so nothing secret).  You can find the model at 

http://itineris.s3.amazonaws.com/en-wiki_model.bin

I used `lda.save('en-wiki_model.bin')` to generate the file. The file is 2.5GB.

Please let me know if I can provide any additional information.

**Comment by bab2min** [comment]
Thank you for sharing your code and data. This allowed me to spot the problem and I commited a new patch. I will release a 0.3.1 patch that fixes the problem soon. Thank you again!
