### ISSUE TITLE
allow for direct pickling of model classes

### ISSUE THREAD

**Issue by cadmusthefounder** [bab2min/tomotopy#101]
currently model.save() allows saving to a file, but sometimes pickled bytes are preferred.

**Comment by bab2min** [comment]
Hi @cadmusthefounder 
Thank you for your suggestion.
I'll add `tomotopy.LDAModel.loads()` and `tomotopy.LDAModel.saves()` method for reading from and writing to `bytes`.

**Comment by bab2min** [comment]
Hi @cadmusthefounder,
New methods `loads()` and `saves()` are added to topic model classes since version 0.11.0.

**Comment by cadmusthefounder** [comment]
thanks for the quick release!
