### ISSUE TITLE
Cannot retrieve the gamma states matrix from inference

### ISSUE THREAD

**Issue by zhenliu2012** [bab2min/tomotopy#102]
Hi I'm new to the tomotopy implementation of LDA models, I'm wondering if there's a way to get the gamma states in addition to the topic distribution from the output of LDAmodel.infer(docs). The topic distribution is normalized to have a sum of probabilities to 1, but what I'm trying to get is the model states gamma before the normalization. 
My use case is that when the unseen doc to be inferred is irrelevant to the train corpus, it'll be likely to have a lower value in the gamma matrix, therefore I can set a threshold to only return topic distribution for more relevant documents. However the current return is normalized so cannot be used like this. 

Any help is appreciated!

**Comment by bab2min** [comment]
Hi @zhenliu2012,
Currently `get_topic_dist()` or `infer()` return a normalized distribution only. But sometimes the unnormalized results is needed, as you said.
I'll add an optional argument `normalize` to `get_topic_dist()` that controls normalization of the result in the next update.
Thank you for your good suggestion.

**Comment by bab2min** [comment]
Now you can get the raw distribution likes:
```python
mdl = tp.LDAModel(...) # create models ...

mdl.train(...) # train models ...

raw_values = mdl.docs[0].get_topic_dist(normalize=False)
```
