### ISSUE TITLE
numpy version mismatch

### ISSUE THREAD

**Issue by benreaves** [bab2min/tomotopy#103]
`python
>>> import tomotopy
RuntimeError Traceback (most recent call last) RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
...
$ pip install numpy==1.20.1
>>> import tomotopy
>>>
`

I think setup.py needs to require that numpy version be >= 1.20.1

**Comment by bab2min** [comment]
It has been fixed since version 0.11.0.
