### ISSUE TITLE
gdmr_both_categorical_and_numerical.py  코드 에러 관련

### ISSUE THREAD

**Issue by ByungjunKim** [bab2min/tomotopy#106]
안녕하세요.
늘 감사한 마음뿐인 김병준입니다.
이번 패키지 업데이트에서 g-dmr이 명목변수도 추가 가능하다는 말을 듣고 코드를 돌려보고 있는데요.

https://github.com/bab2min/tomotopy/blob/main/examples/gdmr_both_categorical_and_numerical.py

위 코드에서 아래 부분이 다음과 같이 에러가 나네요.

```
mdl = tp.GDMRModel(tw=tp.TermWeight.ONE, k=30, degrees=[6], 
    alpha=1e-2, sigma=0.25, sigma0=3.0, decay=1.0,
    metadata_range=[(2000, 2017)], corpus=corpus
)

Exception: `degrees` must be an iterable of int.
```
degrees 파라미터를 바꿔야 할까요?

감사합니다.

**Comment by bab2min** [comment]
안녕하세요 @ByungjunKim 
앗, 제보 감사합니다. 해당 예제를 테스트하는걸 놓쳤었네요. 
입력 인자를 파싱하는 부분에서 문제가 있는 걸로 확인됐구요
일단은 
```python
mdl = tp.GDMRModel(tw=tp.TermWeight.ONE, k=30, degrees=[6], 
    alpha=[1e-2] * 30, sigma=0.25, sigma0=3.0, decay=1.0,
    metadata_range=[(2000, 2017)], corpus=corpus
)
```
로 alpha를 list로 입력해서 문제를 회피할 수 있습니다.

**Comment by bab2min** [comment]
@ByungjunKim 
해당 문제가 해결된 0.11.1 버전을 배포했습니다. 
다시 한번 에러 제보해주신 점에 감사드립니다.

**Comment by ByungjunKim** [comment]
바로 고쳐주셔서 정말 감사합니다. 
논문에 팍팍 반영해보겠습니다.
