### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by ZechyW** [bab2min/tomotopy#108]
Hi @bab2min, It looks like the documentation page for the latest release (https://bab2min.github.io/tomotopy/0.11.1/en/) is down -- Probably an easy fix, but wanted to give you a quick heads up about it!

**Comment by bab2min** [comment]
Hi @ZechyW,
Oops, The redirection had an incorrect address. You can access the documentation page with correct url (https://bab2min.github.io/tomotopy/v0.11.1/en/). 
The redirection has been fixed, but it may take some time to be reflected due to the cache.
Thank you for reporting!
