### ISSUE TITLE
Question on running tomotopy on multiple cores and threads

### ISSUE THREAD

**Issue by cadmusthefounder** [bab2min/tomotopy#110]
In the docs, the following is mentioned:

```
tomotopy can take advantage of multicore CPUs with a SIMD instruction set, which can result in faster iterations.
```

Can you clarify on how to run tomotopy on multiple cores and threads? Will it by default use all the available cores on the machine? An example on how to do this is much appreciated.

**Comment by bab2min** [comment]
Hello @cadmusthefounder ,
`model.train` or `model.infer` method have the `workers` argument, which controls the number of threads using training / inference. Its default value is 0 and it means that all available cores will be used [(documentation)](https://bab2min.github.io/tomotopy/v0.11.1/en/#tomotopy.LDAModel.train).

These methods also have the `parallel` argument, that selects a parallel algorithm for training / inference [(documentation)](https://bab2min.github.io/tomotopy/v0.11.1/en/#tomotopy.ParallelScheme). Many models supports `ParallelScheme.PARTITION` that is effienct for a large number of workers or large models, but other models(HDP, HLDA, PA, HPA) only supports `ParallelScheme.COPY_MERGE` that is a relatively inefficient algorithm.

**Comment by cadmusthefounder** [comment]
@bab2min I am a bit confused with your statements

> method have the workers argument, which controls the number of threads using training / inference

and

> Its default value is 0 and it means that all available cores will be used

which seems to conflict with each other, as from my understanding, each core (aka process) can have multiple threads. So if setting `workers` argument as 0 control the number of cores used, then it shouldn't be able to control the number of threads used for each core.

**Comment by Dobatymo** [comment]
@cadmusthefounder I think tomotopy doesn't use multiple processes, just multiple threads (@bab2min please correct me if I am wrong). It's the operating system's job to distribute the threads to different cores. So if you have 8 cores, running 8 threads should run 1 thread per core. More threads per core won't have any advantage afaik.

**Comment by bab2min** [comment]
@cadmusthefounder 
Sorry for the confusion. As @Dobatymo said, tomotopy doesn't use multi processing, but multi threading.
"All available cores will be used" meant that one thread will be created for each logical core. So ideally, the workload of each thread can be distributed evenly across each core and in this sense, I expressed it as "all cores can be used".

**Comment by cadmusthefounder** [comment]
@bab2min @Dobatymo thanks for the clarification, I understand now :)
