### ISSUE TITLE
Question: How to get unseen docs ll_per_word after infer method?

### ISSUE THREAD

**Issue by SE93WO** [bab2min/tomotopy#111]
Hi.

Currently, Infer method return log-likelihoods each docs. Is there a way to get the unseen docs ll_per_word? 

Thank you.

**Comment by bab2min** [comment]
Hello @SE93WO 
As you said, currently `infer` method returns only log-likelihoods. So you should calculate `ll_per_word` from `log-likelihoods` in the current version.
To do this, you first need to find the number of words in each document to be inferred like:
```python
mdl = tp.LDAModel(...)

# some codes for add_doc and train

doc_to_be_inferred = mdl.make_doc(...)
num_words_of_doc = (doc_to_be_inferred.words < len(mdl.used_vocabs)).sum()
ll, _ = mdl.infer(doc_to_be_inferred)
ll_per_word = ll / num_words_of_doc
```

Actually, the inconsistency of log-likelihoods between train and infer stage is a kind of mistakes in the library design.
I will try to unify it in the next update.
Thank you for your good question.
