### ISSUE TITLE
grammar mistake in attribute error

### ISSUE THREAD

**Issue by RutgerEttes** [bab2min/tomotopy#120]
When running doc.pseudo_doc_id with an LDA model, the error reads "AttributeError: doc doesn't has `pseudoDoc` field!". This should be "doc doesn't have `pseudoDoc` field!" or "doc has no `pseudoDoc` field!".

**Comment by bab2min** [comment]
Hi @RutgerEttes,
Thank you for reporting grammatical errors.
Since I am not a native English speaker, there may be many errors in the document.
I'll fix it in the next update!
If you notice any grammatical errors or better translations related to the documentation, please feel free to report it.
