### ISSUE TITLE
R wrapper

### ISSUE THREAD

**Issue by jwijffels** [bab2min/tomotopy#124]
any plans for an R wrapper for the C++ functionalities?

**Comment by bab2min** [comment]
Hi @jwijffels ,
Unfortunately, I don't know how to handle R, so it would be difficult to write a wrapper for R.
But anyone who knows the R's C/C++ API and writes a wrapper for R base on this repository is always welcome.

**Comment by jwijffels** [comment]
Is the raw src code of tomoto at https://github.com/bab2min/tomotopy/tree/main/src or is the original source code from another repository?

**Comment by bab2min** [comment]
@jwijffels 
Actually, there is a private repo for c++ base of `tomoto`, but it is inaccessible for public. The codes in  https://github.com/bab2min/tomotopy/tree/main/src is the same as that, you can use them freely.

**Comment by jwijffels** [comment]
I'll have a look to see if I can create the Rcpp wrapper. 
Is the C++ code self-sufficient enough or is there a lot in the Python part?

**Comment by bab2min** [comment]
Core functions related to training and inference are gathered on the C++ side in `src/TopicModel`. You can find detailed interfaces in header files (*.h), for example:

https://github.com/bab2min/tomotopy/blob/9592b89c4c86f5c8cf55696669d7d0a1f0779954/src/TopicModel/TopicModel.hpp#L219-L268

https://github.com/bab2min/tomotopy/blob/9592b89c4c86f5c8cf55696669d7d0a1f0779954/src/TopicModel/LDA.h#L172-L191

But utility functions for Python, such as `Corpus`, `Document`, and other wrappers, are grouped in the `src/python` folder. Some utility functions are combined with Python and may have to be newly developed for R.

In fact, the c++ interface is poorly documented. If you have questions about internal implementations, please feel free to ask.

**Comment by jwijffels** [comment]
Thanks. I'll see how far I can get.
