### ISSUE TITLE
Multiple per-topic-word-priors crash jupyter kernel

### ISSUE THREAD

**Issue by ebergam** [bab2min/tomotopy#125]
Hi @bab2min ! 
I was trying to do something similar the [guidedLDA](https://github.com/vi3k6i5/GuidedLDA) model (which I think would be worth adding to `tomotopy`, it is very powerful!). 

I tried to add more then one word prior, with same probability, for several topics, using your [example](https://github.com/bab2min/tomotopy/blob/main/examples/word_prior.py) code. 

As soon as I try to train the model, the kernel dies. I tested the same on two different machines (linux and windows), and I have uploaded data+code [here](https://github.com/ebergam/tp_gLDA_example) for you to replicate.
Am I making a conceptual mistake, or there is a bug? Thank you!

**Comment by bab2min** [comment]
Hi @ebergam 
Thank you for reporting the bug. I'll examine it.

**Comment by bab2min** [comment]
Hi @ebergam,
It has been finally proved that `LDAModel.set_word_prior` causes a crash after `add_doc` called.
I will update the patch that fixes this bug soon.

Thank you again for reporting the bug.
