### ISSUE TITLE
 AttributeError: module 'tomotopy' has no attribute 'LDAModel'

### ISSUE THREAD

**Issue by AnnieKArmstrong** [bab2min/tomotopy#128]
Hi! 

When I import Tomotopy and then try the print(tp.isa), I get an attribute error: "AttributeError: module 'tomotopy' has no attribute 'isa'"

I also get an attribute error when I try to run the model:  AttributeError: module 'tomotopy' has no attribute 'LDAModel'

I've unimported and reimported the package, but I'm not sure what else to do. 

Thanks for your help!

Best,

Annie

PS--I'm an advanced beginner, so I apologize if this is a stupid question.

**Comment by bab2min** [comment]
Hello @AnnieKArmstrong, 
It seems that `tomotopy` wasn't installed properly in your environment.
Could you share your os, python version, and command line you used to install `tomotopy`?
