### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ozls** [bab2min/tomotopy#132]
Hello! First off, thanks for tomotopy, it's really great. I actually used your implementation of LDA and PTM in my thesis, and I wanted to know: how can I cite your project? Would you be open to provide a bibtex snippet or something to that effect? If you're not interrested don't worry about it, I can simply cite the Github usernames of the contributors as authors. Thanks in advance!

**Comment by bab2min** [comment]
Hi @ozls 
Thank you for your attention to this package.
You can cite this package using following doi : https://zenodo.org/badge/latestdoi/186155463 (https://zenodo.org/record/5000206/export/hx#.YQvqTY4zabg)
or GitHub username and repository link.

**Comment by ozls** [comment]
Perfect, thanks!
