### ISSUE TITLE
PTM: Default setting for number of pseudo-documents

### ISSUE THREAD

**Issue by ozls** [bab2min/tomotopy#136]
Should the default really be to have 1 pseudo-document? This makes PTM into the LDA. It's a bit conter-intuitive to have to tweak this parameter in order to have specific behaviour. I think a reasonable default could be 10*K, as Zuo et al. set the numbe rof topics to 100 and the number of pseudo-documents to 1000.

**Comment by bab2min** [comment]
Hi @ozls 
Thank you for your good suggestion. 
I agree that setting default value to 1 is inappropriate and your suggestion has more sense.
I'll change the default value to `10*k` in the next update.
Thank you again.
