### ISSUE TITLE
hLDA 파라미터 질문

### ISSUE THREAD

**Issue by solhakim** [bab2min/tomotopy#137]
@bab2min 
안녕하세요 ㅎㅎ hLDA를 잘 사용하다가 궁금한 점이 있어 이렇게 글 남기게 되었습니다.
gensim의 ldamodel에서의 passes의 기능이 hLDA에서는 burn-in  파라미터와 동일한 것인지 궁금합니다. 
passes는 모델 학습시 전체 코퍼스에서 모델을 학습시키는 빈도를 제어하는 파라미터이고 tomotopy의 hLDA의 burn-in은 파라미터 학습 초기의 Burn-in 단계의 반복 횟수를 얻거나 설정합니다. 라고 되어있는데, 혹 이게 같은 기능인지 궁금합니다 ㅎㅎ

감사합니다.

**Comment by solhakim** [comment]
혹, LDA와 같은 토픽이 hLDA에서 상위 토픽으로 나오려면 어떻게 하면 좋을까요..? 파라미터는 depth 3 gamma 1.0 eta 1.0으로 해보았을때 상위(depth2)가 LDA와는 다르게 단어의 폭이 좁게 나와 질문드립니다.

**Comment by bab2min** [comment]
안녕하세요 @solhakim 님
1) 먼저 gensim과 tomotopy는 둘다 토픽 모델링을 수행하기는 하지만 내부적인 구현에는 상당한 차이가 있다는걸 알려드립니다.
gensim은 변분 베이즈 추론을 기반으로 토픽 분포를 추정하는 반면, tomotopy는 기브스 샘플링을 이용해 추정합니다.
gensim의 passes와 유사한 역할의 인자는 tomotopy에서는 `train()`의 iteration인데요, 둘다 주어진 데이터를 바탕으로 몇 번의 추정을 반복할 것인지를 지정하는 역할을 합니다. 다만 그 규모가 크게 달라요. gensim의 passes는 몇 십에서 몇 백 정도로도 충분히 수렴된 결과를 얻을 수 있지만, tomotopy의 iteration은 일반적으로 몇 백에서 몇 천 번 이상이 되어야 수렴된 결과를 얻을 수 있습니다 (정확한 수치는 데이터에 따라 크게 달라질 수 있습니다).

2) hLDA의 결과를 통제하는건 까다롭고 LDA와 유사하게 나오게 하는건 더 어려울 수 있습니다.
LDA는 먼저 토픽의 개수가 정해진 상태에서 추론을 진행하기 때문에 빠르게 수렴하고 결과를 직접 통제하기 용이합니다. 반면 hLDA는 gamma라는 하이퍼파라미터를 통해 토픽의 개수를 학습 과정에서 탐색해 나가기에 LDA와는 크게 다른 양상을 보입니다. 게다가 LDA의 경우 한 문헌이 총 K 종류의 토픽을 자유롭게 포함하도록 허용하는 반면, hLDA는 각 문헌이 오직 depth 개수만큼(depth=3이면 3종류)의 토픽만 가질 수 있습니다. 이 때문에 여러 주제가 동등한 계층에서 섞여있는 경우를 모델링할 수 없고 이는 hLDA의 결과가 LDA와 크게 달라지는 또 다른 원인이 됩니다.
LDA와 유사하면서 계층 구조를 가진 토픽 모델을 찾으시는 거라면 hLDA보다는 HPA를 사용하시는게 나을 수 있습니다. 단, HPA의 경우 hLDA처럼 명확한 계층 구조를 가지는 토픽을 뽑아내지는 못합니다.
