### ISSUE TITLE
Question: getting documents with highest proportion of a topic from HDPModel

### ISSUE THREAD

**Issue by davidsgrogan** [bab2min/tomotopy#141]
I'm using HDPModel on 14,000 documents. The resulting topics and their frequency across the corpus are good based on domain knowledge. But I'm struggling to get documents that are representative of a topic, where representative means the documents have highest proportion of tokens from that topic.

Borrowing from https://github.com/bab2min/tomotopy/issues/74, I tried this:

```python
hdp = tp.HDPModel(tw=tp.TermWeight.IDF, min_df=6, rm_top=0, gamma=0.5,
                  alpha=0.1, initial_k=10, seed=100)
[hdp.add_doc(words) for words in texts]
hdp.burn_in = 100
hdp.train(1400)

ldamodel, _ = hdp.convert_to_lda(topic_threshold=0.02)
topic_term_dists = np.stack([ldamodel.get_topic_word_dist(k) for k in range(ldamodel.k)])
doc_topic_dists = np.stack([doc.get_topic_dist() for doc in ldamodel.docs])
doc_lengths = np.array([len(doc.words) for doc in ldamodel.docs])
vocab = list(ldamodel.used_vocabs)
term_frequency = ldamodel.used_vocab_freq
  
# Then I try to find the top 2 documents representative of a topic:
top_n_documents = 2
topic_index = 0
print ("For topic %d, representative documents are:"
       % topic_index, [i for i, j in hdp.get_topic_words(topic_index, 4)])
sorted_tuples = sorted(enumerate(doc_topic_dists[:, topic_index]), key=lambda a:a[1], reverse=True)
for tup in sorted_tuples[0:top_n_documents]:
  print(texts[tup[0]], "\n") # all entries in |texts| are passed to hdp.add_doc in line 3 above
```

But no matter which topic_index I use, the top documents are subjectively unrelated to the topic that they supposedly belong to.

Am I misunderstanding something? Is there a better way to get representative documents for a topic?

**Comment by davidsgrogan** [comment]
Ok, this is great info. I didn't realize that the words from the topics with weight < 0.02 were randomly reassigned. I though they were dropped, somehow.

I found that my "top 2 documents representative of a topic" code worked when I trained `LDAModel` from the beginning, which let me avoid `convert_to_lda`. So I'm sticking with `LDAModel`, at least for now, because `LDAModel` gave results as good as or maybe even better than `HDPModel`. But I like your suggestion of more training after calling `convert_to_lda`, that seems like maybe the best of both HDP and LDA.

Your answer indicates that maybe I wasn't training `HDPModel` long enough. When I increased `HDPModel` iterations about 2-3x that of `LDAModel` (2000 to 5000) the results of `HDPModel` didn't change much and were still not as good as `LDAModel` . Have you ever seen a case that needed an even higher multiplier to see more improvement? Like 20x?

Thanks for the library. Thanks for the guidance.

**Comment by bab2min** [comment]
@davidsgrogan 
I think that since `HDPModel` constantly searches for an appropriate `k` value, it generally takes much more iterations to converge that LDA, and its result is often unstable. Thus, with a fixed `k` value, `LDAModel` outperforms `HDPModel` in many situations. So if you can choose an appropriate `k` value manually, `LDAModel` is a better choice. HDP is better than LDA only in that it can automatically detect `k` value.
