### ISSUE TITLE
Semi-supervised LDA (guided / seeded)

### ISSUE THREAD

**Issue by coletl** [bab2min/tomotopy#167]
Thank you for your work on this fantastic package. Would you be able to add a semi-supervised LDA? Here are some references:

 - [Paper introducing guided LDA](https://dl.acm.org/doi/10.5555/2380816.2380844)
 - [Paper introducing seeded LDA (PDF)](https://www.cs.cornell.edu/home/cardie/papers/masa-sentire-2011.pdf)
 - [Guided LDA in Python](https://guidedlda.readthedocs.io/en/latest/)

**Comment by Dobatymo** [comment]
You can already set word priors, see https://github.com/bab2min/tomotopy#pining-topics-using-word-priors=
