### ISSUE TITLE
Why is there a prior distribution for the regression coefficients in SLDAModel?

### ISSUE THREAD

**Issue by jucendrero** [bab2min/tomotopy#171]
The paper that introduced the sLDA model [1] proposes a generative process in which the regression coefficients η are not drawn from any prior distribution (see the figure below). Nonetheless, the [SLDAModel documentation](https://bab2min.github.io/tomotopy/v0.12.2/en/#tomotopy.SLDAModel) in tomotopy makes reference to two parameters, **mu** and **nu_sq**, that are described as the mean and variance of the regression coefficients, respectively. I'm not sure about the interpretation of these parameters, but I assume that they are the mean and variance of a normal distribution that acts as a prior for the η coefficients (which would correspond to equation (5) in @Savvysherpa's [implementation of sLDA](https://github.com/Savvysherpa/slda/blob/master/examples/slda.ipynb)). My question is: why has this prior distribution been introduced in tomotopy's implementation of sLDA? The original paper makes no reference to this. Is there any additional reference that I'm missing? Wouldn't this prior distribution act as a Ridge regularization for the regression, thus making this model qualitatively different from the original sLDA?
 
![slda_generative](https://user-images.githubusercontent.com/42040326/176770597-7adc8c4a-4469-466f-a373-6092a20e3ab7.png)

[1] Mcauliffe, J. D., & Blei, D. M. (2008). Supervised topic models. In Advances in neural information processing systems (pp. 121-128).

**Comment by bab2min** [comment]
Hi @jucendrero, sorry for late answer.
Actually, tomotopy's sLDA implementation is based on [Savvysherpa's one](https://github.com/Savvysherpa/slda/), which is using Collapsed Gibbs sampling(CGS), and it is different from the original one suggested by Mcauliffe and Blei, based on Variational Inference with EM algorithm.
Since the implementation of CGS needs all parameters to be initialized, the argument `mu` and `nuSq` exists for `SLDAModel.__init__` method. However, their initial values have little effect after the sampling steps has passed sufficiently. Therefore, I think, you do not have to worry too much about the initial value, and there will be no problem if you leave the default values of `0` and `1` respectively.

**Comment by jucendrero** [comment]
Thank you for your answer @bab2min! 

I don't think that `mu` and `nuSq` are the initial values of  the parameters  $\eta $ and  $\sigma^2 $ respectively. I haven't checked the code exhaustively, so correct me if I'm wrong, but I see that both `mu` and `nuSq` are used in different parts of the optimization (for example, in [the `optimizeCoef` function](https://github.com/bab2min/tomotopy/blob/3d50ee1633f18189293c4fa7d2b00d7b8d8e97d3/src/TopicModel/SLDAModel.hpp#L90)).  It seems that they are, instead, hyperparameters of a prior distribution over  $\eta $,

$$\begin{equation} \eta_k \sim \mathcal{N} \left( \mu, \nu^2 \right) \end{equation} .$$

Notice that, in [Savvysherpa's derivation of the CGS solution](https://github.com/Savvysherpa/slda/blob/master/examples/slda.ipynb), this normal distribution is present in the joint probability distribution that defines the model, that is, equations (7) - (10). Later, when the full conditional for  $\eta $ is derived in equations (21) - (23), the resulting distribution is

$$\begin{equation} \mathcal{N} \left(\eta \| \Sigma \left( \nu^{-2} \mu \mathbb{1} + \sigma^{-2} Zy \right), \Sigma \right) \end{equation},$$

where  $\Sigma^{-1} = \nu^{-2} I + \sigma^{-2} ZZ^T$ . This is the posterior probability distribution for the problem of Bayesian Linear Regression (I'm following [Bishop's Machine Learning and Pattern Recognition](https://www.microsoft.com/en-us/research/people/cmbishop/prml-book/), section 3.3, equations (3.49) - (3.51)). If we consider the MAP solution for this problem, we would have that the  $\eta $ coefficients are equal to the mean of this distribution (since we are dealing with a normal distribution), i.e.,

$$\begin{equation} \eta_{\text{MAP}} = \Sigma \left( \nu^{-2} \mu \mathbb{1} + \sigma^{-2} Zy \right) \end{equation}.$$

This reduces to the solution of the standard linear regression problem if we consider an infinitely broad prior,  $\nu \to \infty $. In that case, 

$$\begin{equation} \eta_{\text{MAP}} \approx (ZZ^T)^{-1} Zy \end{equation},$$

which are the normal equations for the least squares problem of of  $y = Z^T \eta $. 

Therefore, I would conclude the following: if one wants to consider sLDA with unregularized linear regression, as in the original paper by Mcauliffe & Blei, then one simply has to set `nuSq`  $\to \infty $. The value of `mu` becomes irrelevant in this scenario, but it would be OK to set it to 0. Regularized versions of this model would arise if we set different values of the parameters. In particular, if `mu` is set to 0 and `nuSq` takes finite values, we would get a Ridge regularized version of the linear regression (Bishop, equations (3.52) - (3.55)).

Do you agree?

**Comment by jucendrero** [comment]
Hi @bab2min! Thanks for your reply. I've been recently experimenting with `nu_sq=sys.float_info.max()` (i.e. `nuSq`  $\to \infty $) to recreate the original implementation and results look good.

Unless you want me to write a comment about this in the documentation, I'm going to close this issue since the problem is solved for me. 

Thanks again for your help!
