### ISSUE TITLE
SLDAModel does not accept user defined values for the "nu_sq" parameter

### ISSUE THREAD

**Issue by jucendrero** [bab2min/tomotopy#173]
I'm choosing different values for the `nu_sq` parameter of the `SLDAModel` and I always get the same error:

`RuntimeError: src/TopicModel/SLDAModel.hpp (392): wrong nuSq value (len = 1)`.

The problem is that, in [src/TopicModel/SLDAModel.hpp, lines 378 - 394](https://github.com/bab2min/tomotopy/blob/main/src/TopicModel/SLDAModel.hpp#L378), the first `if` statement makes reference to `args.nuSq`, but the following `else if` statements make reference to `args.mu` instead. Therefore, the only valid option for the `nu_sq` parameter is an empty list, which is the default value. 

I think this was a typo and the error would be fixed if the `else if` statements were `else if (args.nuSq.size() == 1) `and `else if (args.nuSq.size() == F)` instead.

**Comment by bab2min** [comment]
Hi @jucendrero, thank you for reporting bug. Yes, it is a typo.
After some checks, I'll accept your patch!

**Comment by jucendrero** [comment]
Thank you @bab2min! I see that the pull request has been merged, so I’m closing this issue.
