### ISSUE TITLE
PLDA performance/memory issue

### ISSUE THREAD

**Issue by Dobatymo** [bab2min/tomotopy#18]
Hi,
thanks so much for implementing the Partially Labeled LDA model :)

But there seems to be an issue with the `add_docs` method. Firstly it's much slower than any of the other models in this library and there is also a memory issue. After adding only about 300 (not overly long documents) I run out of memory.

I am using `PLDAModel(latent_topics=20, topics_per_label=1)` and the documents added to this point only contain 3 different labels.

**Comment by bab2min** [comment]
Oh, thanks for the fast feedback. I found the bug at init function of PLDAModel. This bug will be fixed the next version soon.

**Comment by Dobatymo** [comment]
Perfect. It's fixed now.
