### ISSUE TITLE
PLDA documentation, order of topics

### ISSUE THREAD

**Issue by Dobatymo** [bab2min/tomotopy#20]
I understand that after training the PLDAModel `k` is the number of latent topics + the topics resulting from the labels (topics_per_label * unique labels).

What is the order of the topics now? For example using `get_topic_word_dist(0)`, would that give me the first latent topic or the first topic of the first label?

Unrelated to this, it would be great if `tomotopy.Dictionary` would get a nicer string representation.

```
>>> plda_model.topic_label_dict
<tomotopy.Dictionary object at 0x0000012034EADD90>
```

It could just be the same output as `list(m.topic_label_dict)` for example.

Thanks again for your great work. I don't think there is any other topic modeling library with that many models and such a great performance.

**Comment by bab2min** [comment]
Thank you for the good advice.
As for the PLDA topic order, the first N topics refer to the N topics of the first label. The latent topic is at the very end. I will improve the documentation.
I will also take advice on string representation `tomotopy.Dictionary` and update it in a more readable form in the next version.

In addition, during the work, I found that the PLDA and LLDA models sometimes assign words to the wrong topic which doesn't belong to corresponding label. I'm fixing the problem and this patch will also be included in the next version.

Thank you again for your attention.
