### ISSUE TITLE
Release v0.12.5

### ISSUE THREAD

**Issue by claudinoac** [bab2min/tomotopy#206]
It's been a while since the fix for aarch64 has been merged and I'm still compiling the package manually to run in my applications.
Can you release this new version? Thanks!

**Comment by bab2min** [comment]
Oops, I totally forgot to release a new version.
Thank you for reminding @claudinoac .
I've deployed dev version of Linux aarch64 to test.pypi.org. Could you test where it works well?

```
pip install --index-url https://test.pypi.org/simple/ tomotopy==0.12.5
```

**Comment by claudinoac** [comment]
Sure I will. Thank you!

**Comment by claudinoac** [comment]
Hey, quick heads up.
The new version is working very well, either in dockerized aarch64 debian (under M1 mac) as well as in k8s (amd64)

**Comment by bab2min** [comment]
@claudinoac thank you for your testing!
I'll release a new product version!
