### ISSUE TITLE
Trying to use PAM model giving by input processed text

### ISSUE THREAD

**Issue by giaccomgl** [bab2min/tomotopy#22]
Hi. I'm trying to implement PAM Model by giving as input a processed text (list of lemmatized words, I removed punctuation and stop words).
```
def topicExtraction(corpus):
    model = tomotopy.PAModel(k=20)
    model.add_doc(corpus)
    model.train()

    print(model.get_topic_words(k, top_n = 20))
```
But it returns error.
Just one thing: This project looks great.

**Comment by bab2min** [comment]
Thank you for your feedback.

The code you shared means following, doesn't it?
```
def topicExtraction(corpus):
    model = tomotopy.PAModel(k=20)
    for doc in corpus:
        model.add_doc(doc)
    model.train()
    for k in range(20):
        print(model.get_topic_words(k, top_n = 20))
```

However, there is a difficulty in reproducing the error. Can you tell me more about what error occurred?

**Comment by giaccomgl** [comment]
Oh sorry. I gave as Input the entire list. I have to give as input each word in list through a a loop.

**Comment by giaccomgl** [comment]
Anyway If I try to run the script, it says that the class PAModel doesn’t
accept ‘k’ as parameter (invalid parameter). How to fix it?

Il giorno lun 2 dic 2019 alle 04:45 bab2min <notifications@github.com> ha
scritto:

**Comment by bab2min** [comment]
Oh, I missed one of the important things in the above answer. `PAModel` doesn't accept `k`, but `k1`, `k2`. You can see the detail information at documentation. (https://bab2min.github.io/tomotopy/v0.4.2/en/#tomotopy.PAModel)
Please try following code:
```
def topicExtraction(corpus):
    model = tomotopy.PAModel(k1=5, k2=50)
    for doc in corpus:
        model.add_doc(doc)
    model.train()
    for k in range(20):
        print(model.get_topic_words(k, top_n=20))
```

**Comment by giaccomgl** [comment]
It works greatly. Thank you.

Il giorno mar 3 dic 2019 alle 02:12 bab2min <notifications@github.com> ha
scritto:
