### ISSUE TITLE
Possible to expose the corpus class?

### ISSUE THREAD

**Issue by stevemarin** [bab2min/tomotopy#23]
Thanks for tomotopy!  I have one small issue though, and that's rebuilding the corpus every time I want to change the model.  Is there a way to do something like this:

```
import tomotopy as tp

corpus = tp.Corpus()
for document in documents:
    corpus.add_doc(document)

model = tp.LDAModel(k=5, corpus=corpus)
model.train(100)
```
Thanks again for a great package!

**Comment by bab2min** [comment]
Thank you for the good idea!
Since each topic model requires slightly different type of document, it seems not easy to make abstract class `Corpus`. But I'll consider the `Corpus` object, which can integrate various different format of documents.
It may take some time so please be patient.

**Comment by bab2min** [comment]
Since version 0.6.0, you can create `tomotopy.utils.Corpus` instance and all topic models in `tomotopy` provide a `corpus` argument. 

Please see details at [documentation](https://bab2min.github.io/tomotopy/v0.6.1/en/utils.html).
