### ISSUE TITLE
How can I get the K2 distribution of topics out of PAModel

### ISSUE THREAD

**Issue by falakmasir** [bab2min/tomotopy#24]
Currently PAModel.infer(doc) returns only K1 numbers + likelihood. I am trying to build an index and I am having difficulty getting K2 numbers out of the infer() method. I looked at the documentation and infer method is directly inherited from LDA. Is there a way to get the document x topic matrix for both K1 and K2 topics?

**Comment by bab2min** [comment]
Thank you for your interest to this repository.
I've noticed lacking of accessor to subtopic informations in PAModel, as you said.
So I will add new methods, which enables access subtopics (k2), for PAModel in the next update.

Until the next update, you can temporarily calculate the subtopic distribution with the following code:

```
import tomotopy as tp
mdl = tp.PAM(k1=5, k2=25)
for docs in corpus:
    mdl.add_doc(docs)
mdl.train(1000)

# first, infer the document
doc_inst = mdl.make_doc(docs_to_be_inferred)
mdl.infer(doc_inst)

# next, count subtopics
subtopic_counts = [0] * mdl.k2
for t in doc_inst.subtopics:
    subtopic_counts[t] += 1

# estimate distribution
total = sum(subtopic_counts)
for i in range(mdl.k2):
    print('Subtopic #{} : {}'.format(i, subtopic_counts[i] / tot))

```

**Comment by bab2min** [comment]
From v0.5.0, `tomotopy.PAModel.infer` returns both K1 distribution and K2 distribution.
You can get both distributions like:
```
pam = PAModel(k1=10, k2=30)
# add_doc ... training ...

(topic_dist, sub_topic_dist), ll = pam.infer(unseen_doc)
```
