### ISSUE TITLE
topic 가중치 메트릭스를 받아올 수 없나요?

### ISSUE THREAD

**Issue by rudvlf0413** [bab2min/tomotopy#3]
안녕하세요, hdp 구현 코드를 찾다가 tomotopy라는 좋은 라이브러리를 발견하게 되었습니다!

sklearn에 있는 LatentDiricheletAllocation처럼 학습 후 각 다큐먼트 및 단어들에 대한 토픽 가중치 메트릭스를 얻고 싶은데 혹시 그러한 기능은 없는지 궁금합니다.

(https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html)

**Comment by bab2min** [comment]
문헌별 토픽 가중치를 얻고 싶으신거라면 infer 메소드를 통해서 구할 수 있습니다.

```
import tomotopy as tp
model = tp.HDPModel()
# model.add_doc 을 통해 모델에 문헌 추가
model.train(2000)
topic_dist_for_docs, loglikelihoods = model.infer(model.docs)
# topic_dist_for_docs는 각 문헌별 토픽 분포 가중치를, 
# loglikelihoods는 그때의 로그가능도를 보여줍니다.

for i, dist in enumerate(topic_dist_for_docs):
    print('Doc #{}'.format(i), dist)
# 각 문헌별 토픽 분포 가중치를 출력합니다.
```

말씀하신 기능이 이게 맞으신지요?

**Comment by rudvlf0413** [comment]
아 저렇게 각 다큐먼트의 토픽 가중치를 구할 수 있군요!
혹시 각 단어에 대한 토픽 가중치는 어떻게 구할 수 있을까요?
단어 하나짜리 가상 다큐먼트를 만들어서 infer하면 될 것 같은데 좀 더 효율적인 방법이 없을까 해서요

**Comment by bab2min** [comment]
음, 단어에 대한 토픽 가중치라는게 조금 애매한데, infer를 이용해서 구할수는 없습니다.
토픽 모델링은 문헌 내의 각 단어가 0~K 사이의 주제 중 하나에 임의로 배정해가면서 전체 모형의 확률이 높은 지점을 찾아가는 과정이기 때문에, 문헌 내의 각 단어는 K개의 주제 중 하나에 배정될 뿐입니다. 따라서 단어가 1개인 문헌을 만들어서 infer를 할 경우, K개 주제 중 임의로 선택된 주제의 가중치만 높게 나오고 나머지 가중치는 0에 가깝게 나오는 결과를 얻을 뿐입니다.

그 대신, 주제별 단어 분포(word distribution of topics)를 이용하는게 더 나을것 같습니다.

```
import tomotopy as tp
import numpy as np

model = tp.HDPModel()
# model.add_doc 을 통해 모델에 문헌 추가 ...
model.train(2000)

mat = np.array([model.get_topic_word_dist(topic_id) for topic_id in range(model.k)])
# 각 토픽별 단어분포 전체를 모아 하나의 matrix로 만듭니다.

for word_id, word in enumerate(model.vocabs):
    topic_weight_for_word = mat[:, word_id] / np.sum(mat[:, word_id])
    # 각 단어에 대해 주제별 가중치를 계산합니다.
    print(word, *["%.3f" % f for f in topic_weight_for_word])
```

이렇게 하면 아마 원하시던 것과 유사하게, 각 단어가 특정 토픽에 나올 가능성을 계산하여 보여줄 수 있습니다.

**Comment by rudvlf0413** [comment]
아아 네 제가 찾던 방법이네요! 친절한 설명 감사합니다! :)
