### ISSUE TITLE
Document-topic matrix for hierarchical LDA

### ISSUE THREAD

**Issue by saralafia** [bab2min/tomotopy#44]
Is there a way to get the topic mixture of each document back out from a hierarchical model? I am training a HLDAModel: 
```
h_mdl = tp.HLDAModel(depth=4,corpus=corpus,seed=1)
    
for i in range(0, 100, 10): #Train the model using Gibbs-sampling
    h_mdl.train(10)
    print('Iteration: {}\tLog-likelihood: {}'.format(i, h_mdl.ll_per_word))
```
I am using the Document class to access instances of documents with the get_topic_dist() method. Is there a way to access a topic mixture of a document at a given depth of the model?

**Comment by bab2min** [comment]
Oh.. currently, get_topic_dist() of HLDAModel returns the depth distribution of a given document. It lacks the method to access which topic is allocated to a certain depth for a given document. 
I'll add a new way to access topic id for a given depth of the document in next version.

**Comment by bab2min** [comment]
Since version 0.7.1, a `path` property has been added at Document class. It helps to access topic IDs assigned to the document of HLDAModel. Here is an example using `path`.

```
h_mdl = tp.HLDAModel(depth=4,corpus=corpus,seed=1)

# some codes for adding docs and training ...

for i, doc in enumerate(h_mdl.docs):
    print('Topic Distribution of Doc #{}'.format(i))
    for topic_id, weight in zip(doc.path, doc.get_topic_dist()):
        print('Topic #{}: {}'.format(topic_id, weight))
```
