### ISSUE TITLE
Partially Labelled LDA (PLDA): 'k' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by dpfens** [bab2min/tomotopy#47]
I received the following error when instantiating a `tomotopy.PLDA` instance:

```bash
python3.5 -i process_pllda.py 
Traceback (most recent call last):
  File "process_pllda.py", line 27, in <module>
    mdl = tp.PLDAModel(k=50)
TypeError: 'k' is an invalid keyword argument for this function
```

The [documentation](https://github.com/bab2min/tomotopy/blob/master/src/python/docs.h#L1918) for [tomotopy.PLDA](https://bab2min.github.io/tomotopy/v0.7.0/en/#tomotopy.PLDAModel) indicates that `k` is a valid keyword argument for the constructor method, but based on the [source code](https://github.com/bab2min/tomotopy/blob/master/src/python/py_PLDA.cpp#L14) it is not.  `k` is also not listed as a valid parameter later in the documentation, but `latent_topics` is ([source](https://github.com/bab2min/tomotopy/blob/master/src/python/docs.h#L1940)).  I am going to assume that `k` should be `latent_topics`.

**Comment by bab2min** [comment]
Thank you for find the bug. The fixing will be included in the next update!
