### ISSUE TITLE
'model.vocabs' gives full list of tokens even if it was filtered 

### ISSUE THREAD

**Issue by Benja1972** [bab2min/tomotopy#54]
'model.vocabs' gives full list of tokens even if it was filtered. At the same time 'num_vocabs' gives number of tokens after filtering. It is confusing as model gives topic-words distribution as list on numbers on 'num_vocabs' and does not provides id2token dictionary. A kind of  'used_vocabs' needed to make any  down-steam analysis on produced topics

**Comment by bab2min** [comment]
Your point makes sense. To avoid confusion, I'll add the `used_vocabs` and `num_used_vocabs` properties into models. Thank you for your good suggestion.

**Comment by Benja1972** [comment]
Thank you for response and proposal!

**Comment by bab2min** [comment]
A new property named `used_vocabs` has been added since version 0.8.0 and the property `num_vocabs` has been deprecated. You can use `len(used_vocabs)` to get the number of vocabs used.

Thank you for your suggestion again!
