### ISSUE TITLE
Error when calling train(0) with LDAModel

### ISSUE THREAD

**Issue by giuseppecarone** [bab2min/tomotopy#55]
Hi, I'm following the example to train and use LDA model. After adding my documents with the method add_doc of LDAModel, when i call mdl.train(0) the code returns error (" Process finished with exit code -1073741819 (0xC0000005) "). I'm using tomotopy==0.7.1 with a python3.7 virtual environment on windows. Thanks

**Comment by bab2min** [comment]
Could you give more information about your error?
If you share your code and data, the error can be reproduced easily, and it will help fix the bug quickly.
