### ISSUE TITLE
DTModel에서 시점별 토픽 분포 계산

### ISSUE THREAD

**Issue by ByungjunKim** [bab2min/tomotopy#57]
안녕하세요 tomotopy, kiwipiepy를 애용하는 대학원생입니다. (bab2min님은 사랑입니다.)
전에 kiwipiepy 관련해서도 질문햇었는데 기억하시나 모르겠네요.

얼마전에 DTModel이 추가되서 기존 gensim에서 너무나 느리게 돌아가던 DTModel을 tomotopy로 돌리니 비약적으로 학습시간이 줄어서 애용하고 있습니다. 정말 감사합니다.

문제는 시각화할때 인데요, 일단 시점별 토픽내 단어들의 분포 변화는 get_topic_word_dist를 활용하면 될거같은데요. 토픽 간의 분포 변화를 알고 싶습니다. 예컨대 이 코드 처럼(https://github.com/GSukr/dtmvisual) time 변화에 따른 토픽들의 비율 변화를 plot으로 그리려 하는데, gensim에서는 문헌별 토픽 분포 파라미터인 gamma_를 가져와서 토픽들의 비율변화를 계산했는데요.

 tomotopy에서는 get_alpha를 바로 활용하면 될까요?  DTModel의 경우 get_topic_dist 함수가 없어서 이렇게 질문 남기네요.

좋은 패키지 만들어주셔서 감사합니다. 얼마전에 송민 교수님과 쓰신 논문도 리뷰중입니다.

**Comment by bab2min** [comment]
안녕하세요, 관심가져주셔서 감사합니다!
제가 개발한 패키지들이 도움이 될 수 있다니 참 기쁘네요 ㅎㅎ
먼저 현재 gensim에서 제공하는 DtmModel은 변분추론을 이용해 파라미터 추정을 하는 반면, tomotopy.DTModel은 SGLD와 깁스 샘플링을 이용해서 파라미터 추정을 하고 있어서 그 구현 방법이 상당히 상이하기 때문에 두 패키지 사이에서 결과차이가 존재할 수 있다는 점 밝히는 바입니다.

링크 주신 dtmvisual 코드를 확인해보니 특정 시점의 토픽 분포를 계산시, 해당 시점에 속한 문헌들의 토픽 분포의 평균으로 계산하고 있습니다. 이와 비슷한 역할을 하는 코드는 다음과 같이 구현할 수 있을 것으로 보입니다.

```
# mdl은 tomotopy.DTModel의 인스턴스라고 가정합니다.

topic_dist_by_time = np.zeros(shape=[num_timepoints, mdl.k], dtype=np.float)
doc_counts_by_time = np.zeros(shape=[num_timepoints], dtype=np.int32)
for doc in mdl.docs:
    doc_counts_by_time[doc.timepoint] += 1
    topic_dist_by_time[doc.timepoint] += doc.get_topic_dist()

topic_dist_by_time /= doc_counts_by_time[:, np.newaxis]

for k in range(mdl.k):
    print('Topic #{}의 시간에 따른 비율 변화'.format(k))
    print(topic_dist_by_time[:, k])
```

gensim dtm과 비교해보니 tomotopy.DTModel에는 이것저것 빠진 메소드, 프로퍼티들이 꽤 있네요. 다음 버전에서 보완하도록 하겠습니다.ㅎㅎ

**Comment by ByungjunKim** [comment]
세상에 이렇게 또 자세히 달아주시다니. 감사합니다. 저도 작게나마 기여하고싶은데 실력을 더 키워보겠습니다.
