### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by jkaupanger** [bab2min/tomotopy#65]
Your HDP model area has a typo: it looks like the `convert_to_lda` and `is_live_topic` methods are exactly the same, although I'm assuming that they're not.

**Comment by jkaupanger** [comment]
![image](https://user-images.githubusercontent.com/49381855/88112350-8b275400-cb64-11ea-83b0-7edbd46719b9.png)

**Comment by bab2min** [comment]
Hi, @jkaupanger, thanks for reporting typo in the document!
It will be corrected in the next update.

**Comment by bab2min** [comment]
The documentation was fixed at version 0.9.0.
