### ISSUE TITLE
Can't set hyperparameter for CTModel

### ISSUE THREAD

**Issue by fanrenaz** [bab2min/tomotopy#67]
TypeError: 'alpha' is an invalid keyword argument for this function

**Comment by bab2min** [comment]
Oh, CTModel doesn't have argument `alpha`, but has `smoothing_alpha`.
The documentation and __doc__ string of CTModel seems to have a typo. I will fix it in the next update.
Thank you for your reporting.

**Comment by bab2min** [comment]
The typo was fixed in version 0.9.1
