### ISSUE TITLE
How is the inputdata preprocessed and structured?

### ISSUE THREAD

**Issue by kaktuseis** [bab2min/tomotopy#70]
To run the script on my own dataset I need to know how the data has to be preprocessed and structured. I am especially interested in the input structure for the dtm.

**Comment by bab2min** [comment]
Each input document of DTM has its `timepoint` and `words`. `Words` are converted into a list of vocab_id (integer) and `timepoint` into an integer with `[0, T)`. Finally the document-term matrices are built by each `timepoint`. So, `T` document-term matrices are created and used for estimating document-topic and topic-term matrices.
I'm not sure if this answer is appropriate for your question. If not, could you give a more detailed explanation to the meaning of "input structure"?

**Comment by kaktuseis** [comment]
Thanks, now I understand the input but I can not see at which lines in the code the document-topics and topic-term matrices are estimated. The topic distance output is very interesting but I also want to know which terms are new in a certain topic. An output of very topic at very timepoint would be of interest.

**Comment by kaktuseis** [comment]
Thank you, this helped a lot!
