### ISSUE TITLE
How do Tomotopy models handle bigrams/trigrams?

### ISSUE THREAD

**Issue by FeryET** [bab2min/tomotopy#72]
Hello.

One of the key aspects of gensim's LDA models are that they are capable of handling bigrams/trigrams via their dictionaries. I have searched through out your documentations but I couldn't find any notes/tutorials that also included using n-grams. I would be grateful if you could help me with this.

Thanks!

**Comment by bab2min** [comment]
Hello @FeryET , you are finding the function similar to [gensim.models.phrases.Phrases](https://radimrehurek.com/gensim/models/phrases.html), aren't you?
Currently `tomotopy` has functions directly relevant to topic models and doesn't provide any phrasing functions such as bigrams or trigrams. So if you want to model using n-gram words, you should preprocess your text with phraser like gensim's Phraser first and feed the result of it into tomotopy's model.

I think it will be useful if tomotopy has similar one. I'll consider adding phraser into tomotopy.
Thank you.

**Comment by FeryET** [comment]
So could I use the Phrases module provided by Gensim for this task + tomotopy? Because Tomotopy's HDP is way superior to Gensim both in time and quality.

**Comment by bab2min** [comment]
Of course you can. 
```
import tomotopy as tp
from gensim.models.phrases import Phrases, Phraser

# `sentences` is a list of your sentences whose type is list of list of str.
sentences = [['a', 'raw', 'text'], ['some', 'sentences']]
# train gensim's phrase model
phrases = Phrases(sentences, min_count=1, threshold=1)
phraser = Phraser(phrases)

# now you can convert your word list into bigram using `phraser[list_of_words]`
hdpmodel = tp.HDPModel(**kwargs)
for sent in sentences:
  hdpmodel.add_doc(phraser[sent])

# train and do your works ...
```
Please replace `sentences` with your input texts. And you may adjust min_count and threshold value for the better bigram result.

**Comment by bab2min** [comment]
Since version 0.10.0, `extract_ngrams` and `concat_ngrams` are added to `tomotopy.utils.Corpus` class.
Please see the example:
https://github.com/bab2min/tomotopy/blob/main/examples/extract_ngram.py
