### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [bab2min/tomotopy#76]
Hey @bab2min, thanks for this awesome library! Just wanted to let you know there are now [Ruby bindings](https://github.com/ankane/tomoto) for it. The code and docs were incredibly easy to follow.

If you have any feedback, feel free to let me know. Thanks!

**Comment by bab2min** [comment]
Hi @ankane , thank you for good Ruby binding.
I'll introduce it on README of this repository for Ruby users!

**Comment by ankane** [comment]
Thanks @bab2min!
