### ISSUE TITLE
Is it possible to use autoLabeler with PAModel?

### ISSUE THREAD

**Issue by cybr17crwlr** [bab2min/tomotopy#79]
So I trained a PAmodel and wanted to use the auto labeller using FoRelevance and PMIExtractor as shown in the Example code for LDAmodel. Is this support available as of now?

**Comment by bab2min** [comment]
Hi @cybr17crwlr ,
Yes, of course you can. Just replace `LDAModel` to `PAModel` and change some parameters related to `LDAModel` with `PAModel`'s one.
If it doesn't work well, it could be a bug, so please report it.
Thank you.
