### ISSUE TITLE
[feature request] Partially Labeled LDA

### ISSUE THREAD

**Issue by Dobatymo** [bab2min/tomotopy#8]
Hi, your library is aweseome!

Would it be possible to implement _Partially Labeled LDA_?
See paper: [Partially labeled topic models for interpretable text mining](https://www.microsoft.com/en-us/research/wp-content/uploads/2011/08/KDD2011-pldp-final.pdf)

It's a generalization and includes standard LDA and Labeled LDA as special cases.

There is an unofficial Java implementation [gdebasis/splda](https://github.com/gdebasis/splda/blob/master/src/org/plda/PLDA.java). I am not 100% confident about its correctness however.

Thanks for your great work.

**Comment by bab2min** [comment]
Oh, hi! Thank you for your attention!
I didn't know about _Partially Labeled LDA_, but it seems interesting!
I will try to implement this model. If you get another good material or code, please let me know.

**Comment by Dobatymo** [comment]
I am currently working on a pure Python implementation based on the above Java code. https://github.com/Dobatymo/python-topic-models
I am trying to implement everything as clear as possible.

**Comment by bab2min** [comment]
PLDAModel was added into package at 0.4.0 version
