### ISSUE TITLE
Problem with HDP model

### ISSUE THREAD

**Issue by Huma97** [bab2min/tomotopy#80]
Hi, @bab2min, thank you for such a great library. I'm trying to train HDP model for my dataset of news written in Russian (don't think it matters but still). But almost every time I train model (no matter what hyperparameters I chose) I see this picture:

<img width="606" alt="Снимок экрана 2020-10-19 в 18 54 05" src="https://user-images.githubusercontent.com/43617648/96475776-146e2580-123d-11eb-97cb-bff1dd5d394b.png">

For some reason at some random iteration log-likelihood becomes nan even though the number of topics is still changing. Also I always see different numbers even though parameter seed is fixed. 
Is this a bug or is there any explanation for this?
Thank you in advance.

**Comment by bab2min** [comment]
Hi @Huma97, thank you for report the bug.
The issue you reported clearly appears to be an error. I want to reproduce it, but it seems difficult without the data.
Could you share your dataset related to the bug? 
If it is difficult to share your entire data, the minimum dataset where the error can be reproduced is okay too.
If you have any private data, you can send it by email. The data you will send is not used for any purposes except debugging, and I plan to completely delete it after fixing the bug.
Thank you again!

**Comment by Huma97** [comment]
I sent the data I used for training to your email. It's only 612 preprocessed texts in Russian (already tokenized, lemmatized, stop words deleted and so on). I should mention that this is only news I collected for one day. So I tried running this model on news I collected for many other days and always witnessed the same 'nan problem'. 

This is the code I use:

```python
import tomotopy as tp
import pickle
import sys

with open('data.pkl', 'rb') as f:
    word_list_lemmatized = pickle.load(f)

hdp = tp.HDPModel(tw=tp.TermWeight.IDF, min_cf=5, rm_top=10,
                 gamma=1, alpha=0.1, initial_k=30, seed=99999)

for vec in word_list_lemmatized:
    hdp.add_doc(vec)

hdp.burn_in = 100
hdp.train(0)
print('Num docs:', len(hdp.docs), ', Vocab size:', hdp.num_vocabs, ', Num words:', hdp.num_words)
print('Removed top words:', hdp.removed_top_words)
print('Training...', file=sys.stderr, flush=True)

mcmc_iter=1000
for i in range(0, mcmc_iter, 100):
    hdp.train(100)
    print('Iteration: {}\tLog-likelihood: {}\tNum. of topics: {}'.format(i, hdp.ll_per_word, hdp.live_k))
```

When I run this code with the same seed several times, I always get the different results.

**Comment by bab2min** [comment]
This was identified as an error that occurs during parallel multiprocessing. It will be fixed in the next update.
Or you can prevent this error now by turning off the multi threading with setting `workers=1`.
Thank you for reporting the bug.

**Comment by Huma97** [comment]
Hi @bab2min, I'm sorry it took me so long to answer. Setting `workers=1` fixed the problem with different results while using the same seed but I'm afraid the 'nan' problem still remains the same. 
If I understood your last comment correctly using this code should fix this bug but it did not. 

``` python
import tomotopy as tp
import pickle
import sys

with open('data.pkl', 'rb') as f:
    word_list_lemmatized = pickle.load(f)

hdp = tp.HDPModel(tw=tp.TermWeight.IDF, min_cf=5, rm_top=10,
                 gamma=1, alpha=0.1, initial_k=30, seed=99999)

for vec in word_list_lemmatized:
    hdp.add_doc(vec)

hdp.burn_in = 100
hdp.train(0, workers=1)
print('Num docs:', len(hdp.docs), ', Vocab size:', hdp.num_vocabs, ', Num words:', hdp.num_words)
print('Removed top words:', hdp.removed_top_words)
print('Training...', file=sys.stderr, flush=True)

mcmc_iter=1000
for i in range(0, mcmc_iter, 100):
    hdp.train(100, workers=1)
    print('Iteration: {}\tLog-likelihood: {}\tNum. of topics: {}'.format(i, hdp.ll_per_word, hdp.live_k)) 
```
I would very grateful if you looked into it once more. Thank you!

**Comment by bab2min** [comment]
Hi @Huma97 !
Actually I found some problems in HDP model's code, and it seems to affect this bug too. 
I think it will be solved in next update surely, but it takes more time. So please wait more.
Thank you!

**Comment by bab2min** [comment]
Hello @Huma97, a version that fixes the reported issue has been uploaded to test.pypi.org. If you want to test it earlier, you can install the dev version.
```
pip3 install --index-url https://test.pypi.org/simple/ tomotopy==0.10.0
```
This dev version will be released as a main version after a few more tests.
