### ISSUE TITLE
Error in CTM

### ISSUE THREAD

**Issue by danielgarel** [bab2min/tomotopy#81]
I am working on a topic modelling project and want to use the Tomotopy implementation of CTM. So far I have succesfully implemented LDA and Pachinko in the same pipeline as CTM but for CTM I am getting the following error. I am uncertain of why this error arises or how to resolve this. We have tried changing the number of topics, the values for eta and introduced 'model.num_beta_sample=5'. I have around 4620 documents for training. Please find the relevant bit of the code below the error.

![image](https://user-images.githubusercontent.com/56274607/97922379-a78a7d80-1d5c-11eb-8756-bdcbd1e4bcdb.png)

`def train_CTM(documents, k, min_cf=0, rm_top=0, eta=0.01, model_burn_in=100, #smoothing_alpha=0.1,
              train_updates = 1000, train_iter = 10):
    
    # instantiate
    model = tp.CTModel(tw=tp.TermWeight.ONE, min_cf=min_cf, rm_top=rm_top, k=k, #smoothing_alpha = smoothing_alpha,
                      eta = eta)

    model.num_beta_sample = 5

    # add documents to model
    for doc in documents: model.add_doc(doc)
    
    # training**
    model.burn_in = model_burn_in
    # initialising 
    model.train(iter=0)
    print('Num docs:', len(model.docs), ', Vocab size:', len(model.used_vocabs), ', Num words:', model.num_words)
    print('Removed top words:', model.removed_top_words)
    print('Training...')
    # actual training 
    for i in range(0, train_updates, train_iter):
        model.train(train_iter)
        if i%100==0:print('Iteration: {}'.format(i))
    return model

def CTM_search(train_docs, test_docs):
    """ Wrapper function for CTM grid search """
    print("Starting CTM grid search ...")

    w = get_num_tokens(train_docs)

    # The GRID
    ks = [50, 100, 150, 200, 300]
    etas = [1/w, 10/w, 0.1/w]
    

    grid_results = pd.DataFrame(columns=["K","eta","perplexity"])

    start = time.time()

    for k in ks:
        startk = time.time()
        for eta in etas:
            print(" ------------------------------------------- ")
            print("| K = " + str(k) + "\t| eta=" + str(eta))
            try:
                model= train_CTM(train_docs, k,
                                eta=eta, 
                                model_burn_in=MODEL_BURN_IN,
                                train_updates = TRAIN_UPDATES, 
                                train_iter = TRAIN_ITERS)
            except Exception as e:
                print("The following error occurred:")
                print(e)
                print("The grid search will skip the current values.")
                grid_results = grid_results.append({"K":k, "eta":eta,"perplexity":np.nan}, 
                                                ignore_index=True)
                continue
            

            ll = get_test_LL(test_docs, model)
            pp = compute_test_pp(ll, test_docs)
            grid_results = grid_results.append({"K":k, "eta":eta,"perplexity":pp}, 
                                                ignore_index=True)
            print("Test perplexity = "+str(pp))

        endk = time.time()
        print("Time elapsed for k="+str(k)+" : " + str(round(endk - startk, 1)) + " s")

    end = time.time()
    print("Time elapsed: " + str(round(end - start, 1)) + " s")
    
    return grid_results`

Would you have any indication of where this may originate from or how to fix it?

Many thanks in advance for any insight you can provide.

**Comment by GiuliaLanzillotta** [comment]
Is there any news on this one?

**Comment by bab2min** [comment]
Thank @danielgarel for reporting the bug and @GiuliaLanzillotta for reminding it.
Umm... it seems there are some potential bugs in the implementation of Truncated Multivariate Normal distribution.

https://github.com/bab2min/tomotopy/blob/e95b656c46c0d486c09f64a7d7718ce0195ed326/src/Utils/TruncMultiNormal.hpp#L10-L69

Normally, truncation domain `[A, B]` satisfies `A <= B`, but sometimes it seems to be broken.
I'll test it with another implementation of Truncated Multivariate Normal function.

**Comment by bab2min** [comment]
@danielgarel, @GiuliaLanzillotta 
The problem was determined to be due to numerical instability of Truncated Multivariate Normal implementation. I have released version 0.10.2 that solved the problem.

https://github.com/bab2min/tomotopy/blob/77fcff050351facdcc17b86910d437f49554f094/src/Utils/TruncMultiNormal.hpp#L10-L67
https://github.com/bab2min/tomotopy/blob/77fcff050351facdcc17b86910d437f49554f094/src/TopicModel/CTModel.hpp#L57-L114
