### ISSUE TITLE
Asymmetric document/topic priors

### ISSUE THREAD

**Issue by rmalouf** [bab2min/tomotopy#88]
A feature request: would it be possible to allow an asymmetric prior for the document/topic distribution? That is, permit a vector (with length = # of topics) be given as the value of alpha in LDAModel (etc.)

Some reasons why one might want that are described, e.g., here:

Hanna M Wallach, David M Mimno, and Andrew  McCallum. 2009. Rethinking LDA: why priors matter.  NIPS'09: Proceedings of the 22nd International Conference on Neural Information Processing Systems. December 2009. Pages 1973–1981.

**Comment by bab2min** [comment]
@rmalouf Thank you for suggesting a new feature!
I'll implement asymmetric prior feature in next major update. Please be patient as it may take some time.
Thank you!

**Comment by bab2min** [comment]
Since version 0.11.0, asymmetric doc-topic priors are supported in various topic models.
See more detail at https://bab2min.github.io/tomotopy/v0.11.0/en/ .
