### ISSUE TITLE
Labels being generated are the same for every topic

### ISSUE THREAD

**Issue by kapadiup** [bab2min/tomotopy#96]
It seems like when I try to use the get_topic_labels using the example provided in the documentation, I am getting the same label for every topic in the train model result.  Can you please let me know if this is how it is supposed to work or how to go about getting the label based on the topic list of words per topic.

**Comment by bab2min** [comment]
Hi, @kapadiup 
Thank you for your interest to this package.
Could you share your code that generates the same labels? It will help you figure out the cause of the error if you share it.
