### ISSUE TITLE
ModuleNotFoundError: No module named any of '_tomotopy_avx2', '_tomotopy_avx', '_tomotopy_sse2', '_tomotopy_none'

### ISSUE THREAD

**Issue by Olivier-Lakoue** [bab2min/tomotopy#97]
Hi,

I just discovert this package with seems great :).

I use Windows 10 / Anaconda / Jupyter, Installation with OK ( ! pip install tomotopy, tomotopy 0.10.2)
==> tomotopy in c:\users\a147701\appdata\local\continuum\anaconda3\lib\site-packages (0.10.2)

I wanted to test it as indicated in the github pag :

    import tomotopy as tp
    print(tp.isa) # prints 'avx2', 'avx', 'sse2' or 'none'

Results : ModuleNotFoundError: No module named any of '_tomotopy_avx2', '_tomotopy_avx', '_tomotopy_sse2', '_tomotopy_none'

So i can do nothing more ...
Do you have a solution ?

Thanks 
Olivier.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-115ce06398ae> in <module>
----> 1 import tomotopy as tp
      2 
      3 #import tomotopy as tp
      4 print(tp.isa) # prints 'avx2', 'avx', 'sse2' or 'none'
      5 

~\Z_Dev\NLP\Tomotopy\tomotopy\__init__.py in <module>
     70 """
     71 
---> 72 from _tomotopy import *
     73 
     74 import tomotopy.utils as utils

ModuleNotFoundError: No module named any of '_tomotopy_avx2', '_tomotopy_avx', '_tomotopy_sse2', '_tomotopy_none'

**Comment by bab2min** [comment]
Hi @Olivier-Lakoue 
I found that the current 0.10.2 version was built incompatible with the old version of numpy.
Could you try to upgrade your numpy?

```
pip install numpy --upgrade
```

**Comment by Olivier-Lakoue** [comment]
Hi bab2min,

Thanks for your quick response.

after reinstalling numpy-1.20.1, it work !

import tomotopy as tp
print(tp.isa) # prints 'avx2', 'avx', 'sse2' or 'none'

Out : avx2

Normal that i just have 'avx2' ?

thanks, i'm gonna try your package, seems to have very nice features on it !!

Olivier.

**Comment by jonaschn** [comment]
The same issue occurred with numpy-1.19.4 and Python 3.8.2.
An update to numpy-1.20.1 solved the issue.
@bab2min Please update the [requirements.txt](https://github.com/bab2min/tomotopy/blob/main/requirements.txt)
This project looks amazing! Thanks for your good work :smiley:

**Comment by bab2min** [comment]
@jonaschn 
Thank you for reporting.
In the next update I'll update the `requriments.txt` to fix the problem.

**Comment by Olivier-Lakoue** [comment]
Hi bab2min,

So i make some tests with tomotopy and it's a very very usefull and robust tool for LDA, congratulations !

I'm a french developper and i would like to deploy LDA topic Modeling with corpus in french.
nltk have french data for dic & stop words so is it possible to uses it for french or we need other models ?

Thanks, regards.

Olivier.
