### ISSUE TITLE
Automatically link the docs to the latest release

### ISSUE THREAD

**Issue by jonaschn** [bab2min/tomotopy#99]
The shortcut to the API docs [bab2min.github.io/tomotopy](https://bab2min.github.io/tomotopy) redirects to

https://bab2min.github.io/tomotopy/v0.10.1/en/
instead of 
https://bab2min.github.io/tomotopy/v0.10.2/en/

Maybe there is some way to redirect automatically to the latest release.

**Comment by bab2min** [comment]
Hi @jonaschn 
Thank you for notifying.
Actually the main doc's link is updated manually now. I'll find the way to redirect automatically.

**Comment by jonaschn** [comment]
Thanks for fixing manually. I'll leave this issue open.
Feel free to close it if you found a way to automate this process.
